# Start from the official golang image to build the Go application
FROM golang:1.22.3 AS build

# Set the current working directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be
# cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source code into the container
COPY . .

# Build the Go app
RUN go build -o main .

# Start a new stage to set up NGINX and serve the built Go application
FROM nginx:alpine

# Remove default NGINX configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy custom NGINX configuration
COPY nginx-qa.conf /etc/nginx/conf.d/

# Copy the built Go binary from the previous stage
COPY --from=build /app/main /usr/share/nginx/html/

# Expose port 80 to the outside world
EXPOSE 80

# Command to start NGINX
CMD ["nginx", "-g", "daemon off;"]
